[ env ]
TERM = "xterm-256color"

[terminal.shell]
program = "tmux"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

[font]
size = 12
normal = { family = "MesloLGS NF" }
bold = { family = "MesloLGS NF", style = "Bold" }
italic = { family = "MesloLGS NF", style = "Italic" }

[general]
import = ["~/.config/alacritty/themes/themes/tokyo_night.toml"]

[terminal]
